from PyQt6 import QtCore, QtWidgets

from ui.validators import OnlyFloats


class Ui_MainWindow(QtWidgets.QWidget):

    def __init__(self, MainWindow, slots):
        super().__init__()
        self.slots = slots(self)
        self.setupUi(MainWindow)
        self.setup_signals()
        self.setup_validators()
        self.temp()

    def setup_signals(self):
        self.pushButton_get_result.clicked.connect(self.slots.pushButton_get_result_slot)  # type: ignore
        self.pushButton_save_changes_to_db.clicked.connect(self.slots.pushButton_save_changes_to_db_slot)  # type: ignore
        vertical_header = self.tableWidget_1.verticalHeader()
        vertical_header.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        vertical_header.customContextMenuRequested["QPoint"].connect(self.slots.table_context_menu_slot)  # type: ignore

    def temp(self):
        factory_list = ('1', '2', '3')
        start_date_list = ('1', '2', '3')
        end_date_list = ('1', '2', '3')
        self.comboBox_factory.addItems(factory_list)
        self.comboBox_start_date.addItems(start_date_list)
        self.comboBox_end_date.addItems(end_date_list)

    def setup_validators(self):
        self.line_edits = (
            self.lineEdit_data_1,
            self.lineEdit_data_2,
            self.lineEdit_data_3,
            self.lineEdit_data_4,
            self.lineEdit_data_5,
            self.lineEdit_data_6,
        )
        for line_edit in self.line_edits:
            line_edit.setValidator(OnlyFloats())

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 572)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_1 = QtWidgets.QTableWidget(parent=self.tab_1)
        self.tableWidget_1.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tableWidget_1.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.tableWidget_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget_1.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked)
        self.tableWidget_1.setTabKeyNavigation(False)
        self.tableWidget_1.setProperty("showDropIndicator", False)
        self.tableWidget_1.setDragDropOverwriteMode(False)
        self.tableWidget_1.setAlternatingRowColors(False)
        self.tableWidget_1.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidget_1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tableWidget_1.setShowGrid(True)
        self.tableWidget_1.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableWidget_1.setWordWrap(False)
        self.tableWidget_1.setCornerButtonEnabled(True)
        self.tableWidget_1.setRowCount(10)
        self.tableWidget_1.setColumnCount(10)
        self.tableWidget_1.setObjectName("tableWidget_1")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(1, 1, item)
        self.tableWidget_1.horizontalHeader().setVisible(True)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.tableWidget_1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_save_changes_to_db = QtWidgets.QGridLayout()
        self.gridLayout_save_changes_to_db.setObjectName("gridLayout_save_changes_to_db")
        self.label_save_changes_to_db_status = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_save_changes_to_db_status.sizePolicy().hasHeightForWidth())
        self.label_save_changes_to_db_status.setSizePolicy(sizePolicy)
        self.label_save_changes_to_db_status.setText("")
        self.label_save_changes_to_db_status.setObjectName("label_save_changes_to_db_status")
        self.gridLayout_save_changes_to_db.addWidget(self.label_save_changes_to_db_status, 0, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_save_changes_to_db_placeholder = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_save_changes_to_db_placeholder.sizePolicy().hasHeightForWidth())
        self.label_save_changes_to_db_placeholder.setSizePolicy(sizePolicy)
        self.label_save_changes_to_db_placeholder.setText("")
        self.label_save_changes_to_db_placeholder.setObjectName("label_save_changes_to_db_placeholder")
        self.gridLayout_save_changes_to_db.addWidget(self.label_save_changes_to_db_placeholder, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.pushButton_save_changes_to_db = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_changes_to_db.sizePolicy().hasHeightForWidth())
        self.pushButton_save_changes_to_db.setSizePolicy(sizePolicy)
        self.pushButton_save_changes_to_db.setObjectName("pushButton_save_changes_to_db")
        self.gridLayout_save_changes_to_db.addWidget(self.pushButton_save_changes_to_db, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_save_changes_to_db)
        self.gridLayout_get_result = QtWidgets.QGridLayout()
        self.gridLayout_get_result.setObjectName("gridLayout_get_result")
        self.verticalLayout_data_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_data_5.setObjectName("verticalLayout_data_5")
        self.label_data_5 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_5.sizePolicy().hasHeightForWidth())
        self.label_data_5.setSizePolicy(sizePolicy)
        self.label_data_5.setObjectName("label_data_5")
        self.verticalLayout_data_5.addWidget(self.label_data_5)
        self.lineEdit_data_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_5.setSizePolicy(sizePolicy)
        self.lineEdit_data_5.setObjectName("lineEdit_data_5")
        self.verticalLayout_data_5.addWidget(self.lineEdit_data_5)
        self.gridLayout_get_result.addLayout(self.verticalLayout_data_5, 3, 3, 1, 1)
        self.verticalLayout_data_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_data_3.setObjectName("verticalLayout_data_3")
        self.label_data_3 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_3.sizePolicy().hasHeightForWidth())
        self.label_data_3.setSizePolicy(sizePolicy)
        self.label_data_3.setObjectName("label_data_3")
        self.verticalLayout_data_3.addWidget(self.label_data_3)
        self.lineEdit_data_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_3.setSizePolicy(sizePolicy)
        self.lineEdit_data_3.setObjectName("lineEdit_data_3")
        self.verticalLayout_data_3.addWidget(self.lineEdit_data_3)
        self.gridLayout_get_result.addLayout(self.verticalLayout_data_3, 4, 2, 1, 1)
        self.verticalLayout_data_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_data_1.setObjectName("verticalLayout_data_1")
        self.label_data_1 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_1.sizePolicy().hasHeightForWidth())
        self.label_data_1.setSizePolicy(sizePolicy)
        self.label_data_1.setObjectName("label_data_1")
        self.verticalLayout_data_1.addWidget(self.label_data_1)
        self.lineEdit_data_1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_1.setSizePolicy(sizePolicy)
        self.lineEdit_data_1.setObjectName("lineEdit_data_1")
        self.verticalLayout_data_1.addWidget(self.lineEdit_data_1)
        self.gridLayout_get_result.addLayout(self.verticalLayout_data_1, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_get_result.addItem(spacerItem, 2, 1, 3, 1)
        self.horizontalLayout_end_date = QtWidgets.QHBoxLayout()
        self.horizontalLayout_end_date.setObjectName("horizontalLayout_end_date")
        self.label_end_date = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_end_date.setObjectName("label_end_date")
        self.horizontalLayout_end_date.addWidget(self.label_end_date, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.comboBox_end_date = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_end_date.sizePolicy().hasHeightForWidth())
        self.comboBox_end_date.setSizePolicy(sizePolicy)
        self.comboBox_end_date.setObjectName("comboBox_end_date")
        self.horizontalLayout_end_date.addWidget(self.comboBox_end_date, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout_get_result.addLayout(self.horizontalLayout_end_date, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_get_result.addItem(spacerItem1, 2, 4, 3, 1)
        self.verticalLayout_data_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_data_4.setObjectName("verticalLayout_data_4")
        self.label_data_4 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_4.sizePolicy().hasHeightForWidth())
        self.label_data_4.setSizePolicy(sizePolicy)
        self.label_data_4.setObjectName("label_data_4")
        self.verticalLayout_data_4.addWidget(self.label_data_4)
        self.lineEdit_data_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_4.setSizePolicy(sizePolicy)
        self.lineEdit_data_4.setObjectName("lineEdit_data_4")
        self.verticalLayout_data_4.addWidget(self.lineEdit_data_4)
        self.gridLayout_get_result.addLayout(self.verticalLayout_data_4, 2, 3, 1, 1)
        self.verticalLayout_data_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_data_2.setObjectName("verticalLayout_data_2")
        self.label_data_2 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_2.sizePolicy().hasHeightForWidth())
        self.label_data_2.setSizePolicy(sizePolicy)
        self.label_data_2.setObjectName("label_data_2")
        self.verticalLayout_data_2.addWidget(self.label_data_2)
        self.lineEdit_data_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_2.setSizePolicy(sizePolicy)
        self.lineEdit_data_2.setObjectName("lineEdit_data_2")
        self.verticalLayout_data_2.addWidget(self.lineEdit_data_2)
        self.gridLayout_get_result.addLayout(self.verticalLayout_data_2, 3, 2, 1, 1)
        self.verticalLayout_data_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_data_6.setObjectName("verticalLayout_data_6")
        self.label_data_6 = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data_6.sizePolicy().hasHeightForWidth())
        self.label_data_6.setSizePolicy(sizePolicy)
        self.label_data_6.setObjectName("label_data_6")
        self.verticalLayout_data_6.addWidget(self.label_data_6)
        self.lineEdit_data_6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_data_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_data_6.setSizePolicy(sizePolicy)
        self.lineEdit_data_6.setObjectName("lineEdit_data_6")
        self.verticalLayout_data_6.addWidget(self.lineEdit_data_6)
        self.gridLayout_get_result.addLayout(self.verticalLayout_data_6, 4, 3, 1, 1)
        self.pushButton_get_result = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_get_result.sizePolicy().hasHeightForWidth())
        self.pushButton_get_result.setSizePolicy(sizePolicy)
        self.pushButton_get_result.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_get_result.setObjectName("pushButton_get_result")
        self.gridLayout_get_result.addWidget(self.pushButton_get_result, 4, 5, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_start_date = QtWidgets.QHBoxLayout()
        self.horizontalLayout_start_date.setObjectName("horizontalLayout_start_date")
        self.label_start_date = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_start_date.setObjectName("label_start_date")
        self.horizontalLayout_start_date.addWidget(self.label_start_date, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.comboBox_start_date = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_start_date.sizePolicy().hasHeightForWidth())
        self.comboBox_start_date.setSizePolicy(sizePolicy)
        self.comboBox_start_date.setObjectName("comboBox_start_date")
        self.horizontalLayout_start_date.addWidget(self.comboBox_start_date, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout_get_result.addLayout(self.horizontalLayout_start_date, 3, 0, 1, 1)
        self.horizontalLayout_factory = QtWidgets.QHBoxLayout()
        self.horizontalLayout_factory.setObjectName("horizontalLayout_factory")
        self.label_factory = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_factory.sizePolicy().hasHeightForWidth())
        self.label_factory.setSizePolicy(sizePolicy)
        self.label_factory.setObjectName("label_factory")
        self.horizontalLayout_factory.addWidget(self.label_factory, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.comboBox_factory = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_factory.sizePolicy().hasHeightForWidth())
        self.comboBox_factory.setSizePolicy(sizePolicy)
        self.comboBox_factory.setObjectName("comboBox_factory")
        self.horizontalLayout_factory.addWidget(self.comboBox_factory, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout_get_result.addLayout(self.horizontalLayout_factory, 2, 0, 1, 1)
        self.verticalLayout_result = QtWidgets.QVBoxLayout()
        self.verticalLayout_result.setObjectName("verticalLayout_result")
        self.label_result = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_result.addWidget(self.label_result)
        self.lineEdit_result = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_result.sizePolicy().hasHeightForWidth())
        self.lineEdit_result.setSizePolicy(sizePolicy)
        self.lineEdit_result.setReadOnly(True)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.verticalLayout_result.addWidget(self.lineEdit_result)
        self.gridLayout_get_result.addLayout(self.verticalLayout_result, 3, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_get_result)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget_1.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget_1.isSortingEnabled()
        self.tableWidget_1.setSortingEnabled(False)
        self.tableWidget_1.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 2"))
        self.pushButton_save_changes_to_db.setText(_translate("MainWindow", "Зберегти зміни у БД"))
        self.label_data_5.setText(_translate("MainWindow", "Дані 5"))
        self.label_data_3.setText(_translate("MainWindow", "Дані 3"))
        self.label_data_1.setText(_translate("MainWindow", "Дані 1"))
        self.label_end_date.setText(_translate("MainWindow", "Кінцева дата"))
        self.label_data_4.setText(_translate("MainWindow", "Дані 4"))
        self.label_data_2.setText(_translate("MainWindow", "Дані 2"))
        self.label_data_6.setText(_translate("MainWindow", "Дані 6"))
        self.pushButton_get_result.setText(_translate("MainWindow", "Розрахувати"))
        self.label_start_date.setText(_translate("MainWindow", "Початкова дата"))
        self.label_factory.setText(_translate("MainWindow", "Підприємство"))
        self.label_result.setText(_translate("MainWindow", "Результат"))
